full python

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -1,74 +1,260 @@
-name: Build Python Installer
+name: Tests
 
+# gh-84728: "paths-ignore" is not used to skip documentation-only PRs, because
+# it prevents to mark a job as mandatory. A PR cannot be merged if a job is
+# mandatory but not scheduled because of "paths-ignore".
 on:
   workflow_dispatch:
   push:
     branches:
-      - 'main'
-      - '3.11'
+    - 'main'
+    - '3.11'
+    - '3.10'
+    - '3.9'
+    - '3.8'
   pull_request:
     branches:
-      - 'main'
-      - '3.11'
+    - 'main'
+    - '3.11'
+    - '3.10'
+    - '3.9'
+    - '3.8'
 
 permissions:
   contents: read
-  actions: write
 
 concurrency:
-  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
+  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}-reusable
   cancel-in-progress: true
 
 jobs:
+  check_source:
+    name: 'Check for source changes'
+    runs-on: windows-latest
+    timeout-minutes: 10
+    outputs:
+      run-docs: ${{ steps.docs-changes.outputs.run-docs || false }}
+      run_tests: ${{ steps.check.outputs.run_tests }}
+      run_ssl_tests: ${{ steps.check.outputs.run_ssl_tests }}
+      config_hash: ${{ steps.config_hash.outputs.hash }}
+    steps:
+      - uses: actions/checkout@v4
+      - name: Check for source changes
+        id: check
+        run: |
+          if [ -z "$GITHUB_BASE_REF" ]; then
+            echo "run_tests=true" >> $GITHUB_OUTPUT
+            echo "run_ssl_tests=true" >> $GITHUB_OUTPUT
+          else
+            git fetch origin $GITHUB_BASE_REF --depth=1
+            git diff --name-only origin/$GITHUB_BASE_REF.. | grep -qvE '(\.rst$|^Doc|^Misc|^\.pre-commit-config\.yaml$|\.ruff\.toml$)' && echo "run_tests=true" >> $GITHUB_OUTPUT || true
+            git diff --name-only origin/$GITHUB_BASE_REF.. | grep -qE '(ssl|hashlib|hmac|^.github)' && echo "run_ssl_tests=true" >> $GITHUB_OUTPUT || true
+          fi
+      - name: Compute hash for config cache key
+        id: config_hash
+        run: |
+          echo "hash=${{ hashFiles('configure', 'configure.ac', '.github/workflows/build.yml') }}" >> $GITHUB_OUTPUT
+      - name: Get a list of the changed documentation-related files
+        if: github.event_name == 'pull_request'
+        id: changed-docs-files
+        uses: Ana06/get-changed-files@v2.3.0
+        with:
+          filter: |
+            Doc/**
+            Misc/**
+            .github/workflows/reusable-docs.yml
+          format: csv  # works for paths with spaces
+      - name: Check for docs changes
+        if: >-
+          github.event_name == 'pull_request'
+          && steps.changed-docs-files.outputs.added_modified_renamed != ''
+        id: docs-changes
+        run: |
+          echo "run-docs=true" >> "${GITHUB_OUTPUT}"
+
+  check-docs:
+    name: Docs
+    needs: check_source
+    if: fromJSON(needs.check_source.outputs.run-docs)
+    uses: ./.github/workflows/reusable-docs.yml
+
+  check_abi:
+    name: 'Check if the ABI has changed'
+    runs-on: windows-latest
+    needs: check_source
+    if: needs.check_source.outputs.run_tests == 'true'
+    steps:
+      - uses: actions/checkout@v4
+      - uses: actions/setup-python@v5
+      - name: Install dependencies
+        run: |
+            choco install abigail-tools
+      - name: Build CPython
+        env:
+          CFLAGS: -g3 -O0
+        run: |
+          # Build Python with the libpython dynamic library
+          ./configure --enable-shared
+          make -j4
+      - name: Check for changes in the ABI
+        id: check
+        run: |
+          if ! make check-abidump; then
+            echo "Generated ABI file is not up to date."
+            echo "Please add the release manager of this branch as a reviewer of this PR."
+            echo ""
+            echo "The up to date ABI file should be attached to this build as an artifact."
+            echo ""
+            echo "To learn more about this check: https://devguide.python.org/setup/#regenerate-the-abi-dump"
+            echo ""
+            exit 1
+          fi
+      - name: Generate updated ABI files
+        if: ${{ failure() && steps.check.conclusion == 'failure' }}
+        run: |
+          make regen-abidump
+      - uses: actions/upload-artifact@v4
+        name: Publish updated ABI files
+        if: ${{ failure() && steps.check.conclusion == 'failure' }}
+        with:
+          name: abi-data
+          path: ./Doc/data/*.abi
+
+  check_generated_files:
+    name: 'Check if generated files are up to date'
+    runs-on: windows-latest
+    timeout-minutes: 60
+    needs: check_source
+    if: needs.check_source.outputs.run_tests == 'true'
+    steps:
+      - uses: actions/checkout@v4
+      - uses: actions/setup-python@v5
+        with:
+          python-version: '3.x'
+      - name: Runner image version
+        run: echo "IMAGE_VERSION=${ImageVersion}" >> $GITHUB_ENV
+      - name: Restore config.cache
+        uses: actions/cache@v4
+        with:
+          path: config.cache
+          key: ${{ github.job }}-${{ runner.os }}-${{ env.IMAGE_VERSION }}-${{ needs.check_source.outputs.config_hash }}-${{ env.pythonLocation }}
+      - name: Install Dependencies
+        run: choco install -y some-dependencies
+      - name: Add ccache to PATH
+        run: echo "PATH=C:\ccache:$PATH" >> $GITHUB_ENV
+      - name: Configure ccache action
+        uses: hendrikmuhs/ccache-action@v1.2
+        with:
+          save: false
+      - name: Configure CPython
+        run: |
+          # Build Python with the libpython dynamic library
+          ./configure --config-cache --with-pydebug --enable-shared
+      - name: Regenerate autoconf files with container image
+        run: make regen-configure
+      - name: Build CPython
+        run: |
+          make -j4 regen-all
+          make regen-stdlib-module-names
+      - name: Check for changes
+        run: |
+          git add -u
+          changes=$(git status --porcelain)
+          # Check for changes in regenerated files
+          if test -n "$changes"; then
+            echo "Generated files not up to date."
+            echo "Perhaps you forgot to run make regen-all or build.bat --regen. ;)"
+            echo "configure files must be regenerated with a specific version of autoconf."
+            echo "$changes"
+            echo ""
+            git diff --staged || true
+            exit 1
+          fi
+      - name: Check exported libpython symbols
+        run: make smelly
+      - name: Check limited ABI symbols
+        run: make check-limited-abi
+
   build_windows:
-    name: 'Build Windows Installer'
+    name: 'Windows'
+    needs: check_source
+    if: needs.check_source.outputs.run_tests == 'true'
+    uses: ./.github/workflows/reusable-windows.yml
+
+  # Suppression des builds Mac et Ubuntu
+  # build_macos:
+  #   name: 'macOS'
+  #   needs: check_source
+  #   if: needs.check_source.outputs.run_tests == 'true'
+  #   uses: ./.github/workflows/reusable-macos.yml
+  #   with:
+  #     config_hash: ${{ needs.check_source.outputs.config_hash }}
+
+  # build_ubuntu:
+  #   name: 'Ubuntu'
+  #   needs: check_source
+  #   if: needs.check_source.outputs.run_tests == 'true'
+  #   uses: ./.github/workflows/reusable-ubuntu.yml
+  #   with:
+  #     config_hash: ${{ needs.check_source.outputs.config_hash }}
+  #     options: |
+  #       ../cpython-ro-srcdir/configure \
+  #         --config-cache \
+  #         --with-pydebug \
+  #         --with-openssl=$OPENSSL_DIR
+
+  # build_ubuntu_ssltests:
+  #   name: 'Ubuntu SSL tests with OpenSSL'
+  #   runs-on: ubuntu-20.04
+  #   timeout-minutes: 60
+  #   needs: check_source
+  #   if: needs.check_source.outputs.run_tests == 'true' && needs.check_source.outputs.run_ssl_tests == 'true'
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       openssl_ver: [1.1.1w, 3.0.13, 3.1.5, 3.2.1]
+  #   env:
+  #     OPENSSL_VER: ${{ matrix.openssl_ver }}
+  #     MULTISSL_DIR: ${{ github.workspace }}/multissl
+  #     OPENSSL_DIR: ${{ github.workspace }}/multissl/openssl/${{ matrix.openssl_ver }}
+  #     CC: gcc
+  #     CFLAGS: -g3 -O0
+  #   steps:
+  #     - uses: actions/checkout@v4
+  #     - uses: actions/setup-python@v5
+  #     - name: Install Dependencies
+  #       run: |
+  #         sudo apt-get install -y pkg-config
+  #     - name: Configure CPython
+  #       run: |
+  #         # Build Python with the libpython dynamic library
+  #         ./configure --enable-shared --with-openssl=${{ env.OPENSSL_DIR }} --with-pydebug
+  #     - name: Build CPython
+  #       run: make -j4
+  #     - name: Run SSL tests
+  #       run: make check-ssl
+
+  all-required-green:
+    name: All required checks pass
+    if: always()
+    needs:
+    - check_source
+    - check_generated_files
+    - build_windows
+
     runs-on: windows-latest
 
     steps:
-      - name: Checkout the repository
-        uses: actions/checkout@v4
-      
-      - name: Download CPython Source
-        run: |
-          git clone --branch v3.11.10 https://github.com/python/cpython.git
-          cd cpython
-
-      - name: Install Visual Studio Build Tools
-        run: |
-          Invoke-WebRequest -Uri https://aka.ms/vs/16/release/vs_buildtools.exe -OutFile vs_buildtools.exe
-          Start-Process vs_buildtools.exe -ArgumentList "--quiet", "--norestart", "--wait", "--add", "Microsoft.VisualStudio.Workload.VCTools", "--add", "Microsoft.VisualStudio.Component.VC142.x86.x64", "--add", "Microsoft.VisualStudio.Component.VC143.x86.x64" -NoNewWindow -Wait
-      
-      - name: Install WiX Toolset 3.5.0 Manually
-        run: |
-          Invoke-WebRequest -Uri "https://github.com/wixtoolset/wix3/releases/download/wix35/wix35.exe" -OutFile wix35.exe
-          Start-Process wix35.exe -ArgumentList "/silent", "/norestart" -Wait
-
-
-      - name: Find Visual Studio installation
-        id: vs_installation
-        shell: powershell
-        run: |
-          $vs_install_path = &"C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath
-          echo "VS_INSTALL_PATH=$vs_install_path" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8
-
-      - name: Configure environment for Visual Studio
-        shell: bash
-        run: |
-          "$VS_INSTALL_PATH/VC/Auxiliary/Build/vcvarsall.bat" amd64
-
-
-      - name: Build Python externa MSI installer
-        run: |
-          cd cpython
-          .\Tools\msi\get_externals.bat
-
-      - name: Build Python MSI installer
-        run: |
-          cd cpython
-          .\Tools\msi\build.bat -x64
-
-      - name: Upload all Artifacts last
-        uses: actions/upload-artifact@v4
-        with:
-          name: python-all-last
-          path: D:\a\cpython\cpython\*
+    - name: Check whether the needed jobs succeeded or failed
+      uses: re-actors/alls-green@05ac9388f0aebcb5727afa17fcccfecd6f8ec5fe
+      with:
+        allowed-failures: >
+          build_windows,
+        allowed-skips: >
+          ${{
+            !fromJSON(needs.check_source.outputs.run-docs)
+            && '
+            check-docs,
+            '
+            || ''
+          }}
