newers

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -59,12 +59,17 @@ jobs:
       - name: Build CPython
         run: |
           cd cpython
-          .\PCbuild\build.bat --pgo || (Write-Error "Build failed. Check the logs for details." && exit 1)
+          .\PCbuild\build.bat -e -d -p arm64 
 
       - name: Générer l'installateur CPython
         run: |
           cd cpython
           & "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\msbuild.exe" "PCbuild\pcbuild.proj" /p:Configuration=Release /t:Build /p:Platform=x64 || (Write-Error "Installer generation failed. Check the logs for details." && exit 1)
+
+      - name: Configurer la disposition de Python
+        run: |
+          cd cpython
+          .\PCbuild\python.bat PC\layout --preset-default --copy "C:\output\python_install" || (Write-Error "Layout generation failed. Check the logs for details." && exit 1)
 
       - name: Upload Executables
         uses: actions/upload-artifact@v4
